export const clerkAppearance = {
  variables: {
    colorPrimary: "#2189e8",
    colorBackground: "#ffffff",
    colorForeground: "#25211d",
    colorMutedForeground: "#77716a",
    colorInputBackground: "#ffffff",
    colorInputForeground: "#25211d",
    borderRadius: "1rem",
    fontFamily: "var(--font-geist-sans)",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "w-full rounded-[2rem] border border-border bg-card px-5 py-6 shadow-none sm:px-7",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    socialButtonsBlockButton: "rounded-full border-border bg-background py-3 font-semibold shadow-none hover:bg-secondary",
    socialButtonsBlockButtonText: "font-semibold",
    dividerLine: "bg-border",
    dividerText: "font-mono text-[0.62rem] uppercase tracking-[0.14em] text-muted-foreground",
    formFieldLabel: "font-medium text-foreground",
    formFieldInput: "rounded-2xl border-border bg-background px-4 py-3 shadow-none focus:border-brand focus:ring-0",
    formButtonPrimary: "rounded-full bg-primary py-3.5 font-semibold text-primary-foreground shadow-none hover:bg-primary/90",
    footerActionText: "text-muted-foreground",
    footerActionLink: "font-semibold text-accent-foreground hover:text-accent-foreground/80",
    identityPreview: "rounded-2xl border-border bg-secondary",
    identityPreviewEditButton: "text-accent-foreground",
    formFieldInputShowPasswordButton: "text-muted-foreground",
    alert: "rounded-2xl",
  },
}
