-- Durable anti-abuse accounting for OpenAI-backed routes.
-- This is intentionally separate from product/free-tier usage counters.

create table if not exists public.ai_spend_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action ~ '^[a-z0-9_]{1,64}$'),
  request_key uuid not null,
  created_at timestamptz not null default now(),
  unique (user_id, action, request_key)
);

create index if not exists ai_spend_events_user_action_created_idx
  on public.ai_spend_events (user_id, action, created_at desc);

alter table public.ai_spend_events enable row level security;
revoke all on table public.ai_spend_events from public, anon, authenticated;
grant select, insert, delete on table public.ai_spend_events to service_role;

create or replace function public.reserve_tellwise_ai_spend(
  p_user_id uuid,
  p_action text,
  p_request_key uuid,
  p_minute_limit integer,
  p_hour_limit integer,
  p_day_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_minute_count integer := 0;
  v_hour_count integer := 0;
  v_day_count integer := 0;
begin
  if p_user_id is null
     or p_request_key is null
     or p_action !~ '^[a-z0-9_]{1,64}$'
     or p_minute_limit < 1
     or p_hour_limit < p_minute_limit
     or p_day_limit < p_hour_limit then
    raise exception 'invalid ai spend guard parameters';
  end if;

  -- Serialize reservations for this user/action. Without this lock, a burst of
  -- parallel Lambdas can all count the same state before any one inserts.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_action, 0));

  if exists (
    select 1
    from public.ai_spend_events e
    where e.user_id = p_user_id
      and e.action = p_action
      and e.request_key = p_request_key
  ) then
    return jsonb_build_object(
      'allowed', true,
      'alreadyReserved', true,
      'retryAfterSeconds', 0,
      'limitedBy', null
    );
  end if;

  select
    count(*) filter (where e.created_at > v_now - interval '1 minute'),
    count(*) filter (where e.created_at > v_now - interval '1 hour'),
    count(*)
  into v_minute_count, v_hour_count, v_day_count
  from public.ai_spend_events e
  where e.user_id = p_user_id
    and e.action = p_action
    and e.created_at > v_now - interval '1 day';

  if v_minute_count >= p_minute_limit then
    return jsonb_build_object('allowed', false, 'retryAfterSeconds', 60, 'limitedBy', 'minute');
  end if;
  if v_hour_count >= p_hour_limit then
    return jsonb_build_object('allowed', false, 'retryAfterSeconds', 3600, 'limitedBy', 'hour');
  end if;
  if v_day_count >= p_day_limit then
    return jsonb_build_object('allowed', false, 'retryAfterSeconds', 86400, 'limitedBy', 'day');
  end if;

  insert into public.ai_spend_events (user_id, action, request_key)
  values (p_user_id, p_action, p_request_key);

  return jsonb_build_object(
    'allowed', true,
    'alreadyReserved', false,
    'retryAfterSeconds', 0,
    'limitedBy', null
  );
end;
$$;

revoke all on function public.reserve_tellwise_ai_spend(uuid, text, uuid, integer, integer, integer)
from public, anon, authenticated;
grant execute on function public.reserve_tellwise_ai_spend(uuid, text, uuid, integer, integer, integer)
to service_role;
